// Game Initializer - Create new game with default values

import { 
  GameState, Kingdom, Ruler, Capital, RulerSkills, NobleCouncil, Market, GameTime, Army, Unit, UnitType, 
  Bloodline, House, Hero, Guild, Tavern, Academy, WorldMap, CourtSystem, NobleHouse, EnemyDynasty, SuccessionLaw,
  InfluenceSystem, GeneralLedger, Continent, Estate, EnvironmentalNode, NobleRank, Species, Marriage
} from '../shared/types';
import { 
  INITIAL_RESOURCES, NOBLE_HOUSES, ENEMY_DYNASTIES, SUCCESSION_LAWS, 
  HEIR_INCUBATION_MONTHS, INFLUENCE_SETTINGS
} from '../shared/constants';
import { GameManager } from '../game/manager';

export function initializeNewGame(rulerName: string, kingdomName: string): GameState {
  const rulerSkills: RulerSkills = {
    leadership: 70,
    diplomacy: 60,
    military: 65,
    wisdom: 70,
    charisma: 75,
  };

  const ruler: Ruler = {
    id: `ruler_${Date.now()}`,
    name: rulerName,
    title: 'King',
    age: 35,
    reign: 5,
    skills: rulerSkills,
    traits: ['Wise', 'Just'],
    consort: null,
    heir: null,
    legitimacy: 1.0,
  };

  const capital: Capital = {
    id: `capital_${Date.now()}`,
    name: `${kingdomName} Capital`,
    buildings: [
      {
        id: 'castle_main',
        type: 'castle' as any,
        level: 1,
        constructionProgress: 100,
        productionMultiplier: 1.0,
        maintenanceCost: 50,
        isConstructing: false,
      },
      {
        id: 'farm_main',
        type: 'farm' as any,
        level: 2,
        constructionProgress: 100,
        productionMultiplier: 1.2,
        maintenanceCost: 20,
        isConstructing: false,
      },
      {
        id: 'market_main',
        type: 'market' as any,
        level: 1,
        constructionProgress: 100,
        productionMultiplier: 1.0,
        maintenanceCost: 25,
        isConstructing: false,
      },
    ],
    population: 5000,
    prosperity: 70,
    defense: 50,
    court: {
      id: `court_${Date.now()}`,
      throneRoomLevel: 1,
      courtMembers: [],
      ceremonies: [],
      prestige: 50,
    },
    academy: {
      id: `academy_${Date.now()}`,
      name: `${kingdomName} Academy of Magic`,
      level: 1,
      students: [],
      courses: [],
      knowledgePool: 100,
    },
  };

  const kingdom: Kingdom = {
    id: `kingdom_${Date.now()}`,
    name: kingdomName,
    ruler,
    capital,
    resources: { ...INITIAL_RESOURCES },
    treasury: 10000,
    population: 5000,
    stability: 75,
    diplomacy: [],
    species: Species.HUMAN,
    createdAt: Date.now(),
    lastUpdated: Date.now(),
    namedHouses: [],
    prophecyCountdown: {
      id: `prophecy_${Date.now()}`,
      kingdomsConquered: 0,
      endOfDaysTriggered: false,
      lastUpdateDate: Date.now(),
      milestoneEvents: [
        { id: 'milestone_1', kingdomsRequired: 3, name: 'First Conquest', description: 'Secure three kingdoms', triggered: false },
        { id: 'milestone_2', kingdomsRequired: 6, name: 'Rising Emperor', description: 'Secure six kingdoms', triggered: false },
        { id: 'milestone_3', kingdomsRequired: 10, name: 'End of Days', description: 'Secure all ten kingdoms', triggered: false },
      ],
    },
  };

  const otherKingdoms: Kingdom[] = [
    {
      id: 'kingdom_evermere',
      name: 'Evermere',
      ruler: {
        id: 'ruler_evermere',
        name: 'High Queen Alariel',
        title: 'Queen',
        age: 120,
        reign: 40,
        skills: { leadership: 78, diplomacy: 88, military: 70, wisdom: 95, charisma: 82 },
        traits: ['Graceful', 'Arcane'],
        consort: null,
        heir: null,
        legitimacy: 0.93,
        species: Species.ELF,
        house: 'Silver-Leaf',
        rank: NobleRank.MARQUIS,
      },
      capital: {
        id: 'capital_evermere',
        name: 'Evermere Palace',
        buildings: [],
        population: 4200,
        prosperity: 82,
        defense: 64,
        court: {
          id: 'court_evermere',
          throneRoomLevel: 3,
          courtMembers: [],
          ceremonies: [],
          prestige: 95,
        },
        academy: {
          id: 'academy_evermere',
          name: 'Evermere Arcane Academy',
          level: 4,
          students: [],
          courses: [],
          knowledgePool: 230,
        },
      },
      resources: { ...INITIAL_RESOURCES, gold: 8200, food: 2600, mana: 560 },
      treasury: 16000,
      population: 4200,
      stability: 82,
      diplomacy: [],
      species: Species.ELF,
      createdAt: Date.now() - 20000000,
      lastUpdated: Date.now() - 500000,
    },
    {
      id: 'kingdom_stonehold',
      name: 'Stonehold',
      ruler: {
        id: 'ruler_stonehold',
        name: 'Thane Durin',
        title: 'Thane',
        age: 180,
        reign: 65,
        skills: { leadership: 74, diplomacy: 55, military: 92, wisdom: 80, charisma: 68 },
        traits: ['Stalwart', 'Stubborn'],
        consort: null,
        heir: null,
        legitimacy: 0.88,
        species: Species.DWARF,
        house: 'Stone-Skin',
        rank: NobleRank.COUNT,
      },
      capital: {
        id: 'capital_stonehold',
        name: 'Stonehold Keep',
        buildings: [],
        population: 3800,
        prosperity: 76,
        defense: 78,
        court: {
          id: 'court_stonehold',
          throneRoomLevel: 2,
          courtMembers: [],
          ceremonies: [],
          prestige: 82,
        },
        academy: {
          id: 'academy_stonehold',
          name: 'Stonehold Smithery',
          level: 2,
          students: [],
          courses: [],
          knowledgePool: 90,
        },
      },
      resources: { ...INITIAL_RESOURCES, gold: 7200, stone: 1300, iron: 850 },
      treasury: 13500,
      population: 3800,
      stability: 77,
      diplomacy: [],
      species: Species.DWARF,
      createdAt: Date.now() - 32000000,
      lastUpdated: Date.now() - 800000,
    },
    {
      id: 'kingdom_ironclad',
      name: 'Ironclad',
      ruler: {
        id: 'ruler_ironclad',
        name: 'Warlord Gharok',
        title: 'Chieftain',
        age: 58,
        reign: 12,
        skills: { leadership: 67, diplomacy: 45, military: 96, wisdom: 54, charisma: 60 },
        traits: ['Fierce', 'Ruthless'],
        consort: null,
        heir: null,
        legitimacy: 0.72,
        species: Species.ORC,
        house: 'Wild-Claw',
        rank: NobleRank.BARON,
      },
      capital: {
        id: 'capital_ironclad',
        name: 'Ironclad Fortress',
        buildings: [],
        population: 4600,
        prosperity: 69,
        defense: 88,
        court: {
          id: 'court_ironclad',
          throneRoomLevel: 2,
          courtMembers: [],
          ceremonies: [],
          prestige: 70,
        },
        academy: {
          id: 'academy_ironclad',
          name: 'Ironclad Forge Hall',
          level: 1,
          students: [],
          courses: [],
          knowledgePool: 30,
        },
      },
      resources: { ...INITIAL_RESOURCES, gold: 5000, iron: 400, food: 1800 },
      treasury: 11000,
      population: 4600,
      stability: 65,
      diplomacy: [],
      species: Species.ORC,
      createdAt: Date.now() - 24000000,
      lastUpdated: Date.now() - 700000,
    },
    {
      id: 'kingdom_whisperwood',
      name: 'Whisperwood',
      ruler: {
        id: 'ruler_whisperwood',
        name: 'Lady Seraphine',
        title: 'Duchess',
        age: 72,
        reign: 22,
        skills: { leadership: 80, diplomacy: 90, military: 58, wisdom: 85, charisma: 84 },
        traits: ['Mystical', 'Benevolent'],
        consort: null,
        heir: null,
        legitimacy: 0.95,
        species: Species.HALF_ELF,
        house: 'Silver-Leaf',
        rank: NobleRank.MARQUIS,
      },
      capital: {
        id: 'capital_whisperwood',
        name: 'Whisperwood Glade',
        buildings: [],
        population: 3500,
        prosperity: 88,
        defense: 54,
        court: {
          id: 'court_whisperwood',
          throneRoomLevel: 3,
          courtMembers: [],
          ceremonies: [],
          prestige: 90,
        },
        academy: {
          id: 'academy_whisperwood',
          name: 'Whisperwood Grove',
          level: 3,
          students: [],
          courses: [],
          knowledgePool: 170,
        },
      },
      resources: { ...INITIAL_RESOURCES, gold: 10500, mana: 420, silver: 700 },
      treasury: 14800,
      population: 3500,
      stability: 84,
      diplomacy: [],
      species: Species.HALF_ELF,
      createdAt: Date.now() - 15000000,
      lastUpdated: Date.now() - 300000,
    },
    {
      id: 'kingdom_starlight',
      name: 'Starlight',
      ruler: {
        id: 'ruler_starlight',
        name: 'Lord Fenwick',
        title: 'Earl',
        age: 54,
        reign: 18,
        skills: { leadership: 69, diplomacy: 74, military: 65, wisdom: 72, charisma: 76 },
        traits: ['Clever', 'Charming'],
        consort: null,
        heir: null,
        legitimacy: 0.90,
        species: Species.GNOME,
        house: 'Wind-Walker',
        rank: NobleRank.EARL,
      },
      capital: {
        id: 'capital_starlight',
        name: 'Starlight Court',
        buildings: [],
        population: 3100,
        prosperity: 78,
        defense: 58,
        court: {
          id: 'court_starlight',
          throneRoomLevel: 2,
          courtMembers: [],
          ceremonies: [],
          prestige: 74,
        },
        academy: {
          id: 'academy_starlight',
          name: 'Starlight Observatory',
          level: 2,
          students: [],
          courses: [],
          knowledgePool: 120,
        },
      },
      resources: { ...INITIAL_RESOURCES, gold: 9000, wood: 900, silver: 850 },
      treasury: 12300,
      population: 3100,
      stability: 76,
      diplomacy: [],
      species: Species.GNOME,
      createdAt: Date.now() - 18000000,
      lastUpdated: Date.now() - 600000,
    },
  ];

  const council: NobleCouncil = {
    id: `council_${Date.now()}`,
    nobles: [
      {
        id: 'noble_1',
        name: 'Lord Marcus',
        title: 'Grand Duke',
        power: 85,
        wealth: 5000,
        loyalty: 80,
        traits: ['Ambitious', 'Honorable'],
        faction: 'loyalists',
      },
      {
        id: 'noble_2',
        name: 'Lady Eleanor',
        title: 'Duchess',
        power: 70,
        wealth: 3000,
        loyalty: 75,
        traits: ['Shrewd', 'Diplomatic'],
        faction: 'merchants',
      },
    ],
    influence: new Map([
      ['loyalists', 60],
      ['merchants', 40],
    ]),
    factions: [
      {
        id: 'faction_loyalists',
        name: 'Loyalists',
        members: ['noble_1'],
        influence: 60,
        goals: ['Strengthen the Crown', 'Expand Territory'],
      },
      {
        id: 'faction_merchants',
        name: 'Merchant Guild',
        members: ['noble_2'],
        influence: 40,
        goals: ['Increase Trade', 'Reduce Taxes'],
      },
    ],
  };

  const market: Market = {
    id: `market_${Date.now()}`,
    goods: [
      { id: 'wheat', name: 'Wheat', type: 'food', quantity: 1000, basePrice: 10 },
      { id: 'gold_coin', name: 'Gold Coin', type: 'currency', quantity: 5000, basePrice: 1 },
      { id: 'timber', name: 'Timber', type: 'resource', quantity: 800, basePrice: 15 },
      { id: 'stone', name: 'Stone', type: 'resource', quantity: 500, basePrice: 20 },
      { id: 'iron', name: 'Iron', type: 'resource', quantity: 300, basePrice: 30 },
    ],
    prices: new Map([
      ['wheat', 10],
      ['gold_coin', 1],
      ['timber', 15],
      ['stone', 20],
      ['iron', 30],
    ]),
    tradingRoutes: [],
    merchants: [],
  };

  const mainArmy: Army = {
    id: `army_main_${Date.now()}`,
    name: 'Royal Army',
    units: [
      { id: 'unit_inf_1', type: UnitType.INFANTRY, count: 500, health: 100, training: 75 },
      { id: 'unit_cav_1', type: UnitType.CAVALRY, count: 100, health: 100, training: 80 },
      { id: 'unit_arch_1', type: UnitType.ARCHER, count: 200, health: 100, training: 70 },
    ],
    commander: {
      id: 'commander_1',
      name: 'General Robert',
      rank: 'General',
      experience: 85,
      skills: [80, 75, 85],
    },
    morale: 85,
    readiness: 80,
  };

  const gameTime: GameTime = {
    year: 1000,
    month: 6,
    day: 15,
    hour: 12,
    minute: 0,
    speed: 1,
  };

  const bloodlines: Bloodline[] = [
    {
      id: 'bloodline_main',
      name: `House ${kingdomName}`,
      members: [],
      prestige: 100,
      traits: [],
    },
  ];

  const houses: House[] = [
    {
      id: 'house_main',
      name: `House ${kingdomName}`,
      sigil: '⚜️',
      words: 'Honor, Duty, Legacy',
      members: [{ id: 'lord_1', name: rulerName, title: 'Lord', age: 35, skills: [70, 60, 65] }],
      power: 80,
      wealth: 10000,
      landedTitles: ['Capital', 'Northern Province'],
    },
  ];

  const heroes: Hero[] = [
    {
      id: 'hero_main',
      name: 'Champion of the Realm',
      title: 'Legendary Warrior',
      level: 10,
      experience: 5000,
      skills: [
        { id: 'skill_1', name: 'Swordsmanship', level: 10, effect: '+50% melee damage' },
        { id: 'skill_2', name: 'Leadership', level: 8, effect: '+20% unit morale' },
      ],
      equipment: [],
      story: 'A legendary warrior of great renown',
    },
  ];

  const guilds: Guild[] = [
    {
      id: 'guild_merchants',
      name: 'Merchant Guild',
      type: 'merchants' as any,
      level: 2,
      members: [],
      treasury: 5000,
      quests: [],
    },
    {
      id: 'guild_mages',
      name: 'Circle of Mages',
      type: 'mages' as any,
      level: 1,
      members: [],
      treasury: 2000,
      quests: [],
    },
  ];

  const tavern: Tavern = {
    id: `tavern_${Date.now()}`,
    name: `The Crowned Lion`,
    level: 2,
    patrons: [],
    rumors: [],
    treasury: 1000,
  };

  const worldMap: WorldMap = {
    id: `map_${Date.now()}`,
    regions: [
      { id: 'region_1', name: 'Capital Region', type: 'urban', population: 10000, resources: { gold: 100, food: 500 }, controlled_by: kingdom.id },
      { id: 'region_2', name: 'Northern Lands', type: 'forest', population: 5000, resources: { wood: 300, food: 200 }, controlled_by: kingdom.id },
      { id: 'region_3', name: 'Mountain Hold', type: 'mountain', population: 3000, resources: { stone: 400, iron: 150 }, controlled_by: kingdom.id },
    ],
    playerTerritories: [
      { id: 'territory_1', name: 'Capital', regionId: 'region_1', prosperity: 80, defenses: 90 },
    ],
  };

  const gameState: GameState = {
    kingdom,
    otherKingdoms,
    armies: [mainArmy],
    council,
    market,
    gameTime,
    events: [],
    bloodlines,
    houses,
    heroes,
    guilds,
    tavern,
    worldMap,
    marriages: [],
    // New systems initialization
    nobleHouses: (NOBLE_HOUSES as any[]).map((house, index) => ({
      ...house,
      leaderName: [
        'Duke Alistair',
        'Marquis Vivienne',
        'Count Halwyn',
        'Baron Rowan',
        'Earl Seraph',
        'Duke Kellan',
        'Marquis Moria',
        'Count Lysandra',
        'Baron Toren',
        'Earl Brynna',
        'Duke Hroth',
        'Marquis Keira',
        'Count Orin',
        'Baron Asha',
        'Earl Thorne',
      ][index],
      leaderTitle: [
        'Duke',
        'Marquis',
        'Count',
        'Baron',
        'Earl',
        'Duke',
        'Marquis',
        'Count',
        'Baron',
        'Earl',
        'Duke',
        'Marquis',
        'Count',
        'Baron',
        'Earl',
      ][index],
      kingdomId: [
        kingdom.id,
        kingdom.id,
        otherKingdoms[0].id,
        otherKingdoms[1].id,
        otherKingdoms[2].id,
        otherKingdoms[3].id,
        otherKingdoms[4].id,
        kingdom.id,
        otherKingdoms[0].id,
        otherKingdoms[1].id,
        otherKingdoms[2].id,
        otherKingdoms[3].id,
        otherKingdoms[4].id,
        kingdom.id,
        otherKingdoms[0].id,
      ][index],
      relationship: index === 0 ? 75 : Math.floor(Math.random() * 100),
      members: [
        {
          id: `house_member_${index}_leader`,
          name: [
            'Alistair Storm',
            'Vivienne Gold',
            'Halwyn Stone',
            'Rowan Graves',
            'Seraph Dawn',
            'Kellan Iron',
            'Moria Frost',
            'Lysandra Vale',
            'Toren Ash',
            'Brynna Moon',
            'Hroth Mountain',
            'Keira Swift',
            'Orin Birch',
            'Asha Ember',
            'Thorne Black',
          ][index],
          title: [
            'Duke',
            'Marquis',
            'Count',
            'Baron',
            'Earl',
            'Duke',
            'Marquis',
            'Count',
            'Baron',
            'Earl',
            'Duke',
            'Marquis',
            'Count',
            'Baron',
            'Earl',
          ][index],
          age: 45 + index,
          skills: [60 + index, 55 + index, 65],
        },
      ],
    })),
    enemyDynasties: (ENEMY_DYNASTIES as any[]).map(dynasty => ({
      ...dynasty,
      isAtWar: false,
      relations: Math.floor(Math.random() * 50) - 50,
    })),
    successionLaw: SUCCESSION_LAWS.PRIMOGENITURE as any,
    influenceSystem: {
      currentInfluence: 30,
      sources: [],
      backlashCounter: 0,
      internalFriction: 5,
      externalBacklash: 0,
    },
    generalLedger: {
      id: `ledger_${Date.now()}`,
      entries: [
        {
          id: 'entry_initial',
          date: Date.now(),
          description: 'Kingdom founding capital',
          category: 'income',
          amount: 10000,
        },
      ],
      totalIncome: 10000,
      totalExpense: 0,
      netBalance: 10000,
      lastUpdated: Date.now(),
    },
    continents: [
      {
        id: 'continent_main',
        name: 'Aethelgard',
        kingdoms: [kingdom, ...otherKingdoms],
        environmentalHazards: [
          { id: 'node_1', type: 'beast_nest', location: { x: 50, y: 30 }, difficulty: 5, threat: 40 },
          { id: 'node_2', type: 'river', location: { x: 75, y: 60 }, difficulty: 0, resources: { food: 500 } },
          { id: 'node_3', type: 'mountain', location: { x: 20, y: 80 }, difficulty: 3, resources: { stone: 300, iron: 100 } },
        ],
      },
    ],
    estates: [
      {
        id: 'estate_1',
        name: 'Northern Estate',
        location: { x: 40, y: 20 },
        owner: kingdom.ruler.id,
        prosperity: 65,
        defenses: 50,
        population: 3000,
        resources: { gold: 500, food: 800, wood: 400 },
      },
    ],
  };

  const manager = new GameManager(gameState);
  manager.initializeImperialOverview();
  manager.initializeImperialPillars();
  manager.initializeConstellationMastery();

  return gameState;
}

